# Generated by Django 6.0.2 on 2026-02-27 15:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=50, unique=True)),
                ('position', models.CharField(choices=[('MANAGER', 'Manager'), ('SALESPERSON', 'Salesperson'), ('WAREHOUSE', 'Warehouse Staff'), ('ACCOUNTANT', 'Accountant'), ('SUPERVISOR', 'Supervisor')], max_length=20)),
                ('department', models.CharField(choices=[('SALES', 'Sales'), ('WAREHOUSE', 'Warehouse'), ('ACCOUNTING', 'Accounting'), ('MANAGEMENT', 'Management')], max_length=20)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('date_hired', models.DateField(auto_now_add=True)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['department', 'position'],
            },
        ),
    ]
